// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/[slug]/p.tsx";
import * as $2 from "./routes/admin.tsx";
import * as $3 from "./routes/api/cart/index.ts";
import * as $4 from "./routes/api/cart/items.ts";
import * as $5 from "./routes/cart.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/inspect-vscode.ts";
import * as $8 from "./routes/live/login.tsx";
import * as $9 from "./routes/live/login/success.tsx";
import * as $10 from "./routes/search.tsx";
import * as $11 from "./routes/start.tsx";
import * as $$0 from "./islands/AddToCart.tsx";
import * as $$1 from "./islands/Alert.tsx";
import * as $$2 from "./islands/AuthListener.tsx";
import * as $$3 from "./islands/Editor.tsx";
import * as $$4 from "./islands/InspectVSCode.tsx";
import * as $$5 from "./islands/LoginButtons.tsx";
import * as $$6 from "./islands/Minicart.tsx";
import * as $$7 from "./islands/ProductInformation.tsx";
import * as $$8 from "./islands/SearchBar.tsx";
import * as $$9 from "./islands/SearchControls.tsx";
import * as $$10 from "./islands/VideoCarousel.tsx";
import * as $$$0 from "./components/Banner.tsx";
import * as $$$1 from "./components/BannerGridImages.tsx";
import * as $$$2 from "./components/BannerImg.tsx";
import * as $$$3 from "./components/Footer.tsx";
import * as $$$4 from "./components/GetStarted.tsx";
import * as $$$5 from "./components/Head.tsx";
import * as $$$6 from "./components/Header.tsx";
import * as $$$7 from "./components/HomeFilter.tsx";
import * as $$$8 from "./components/IconCart.tsx";
import * as $$$9 from "./components/ListLinks.tsx";
import * as $$$10 from "./components/MarcasConvidadas.tsx";
import * as $$$11 from "./components/Newsletter.tsx";
import * as $$$12 from "./components/ProductCard.tsx";
import * as $$$13 from "./components/ProductDetails.tsx";
import * as $$$14 from "./components/ProductGallery.tsx";
import * as $$$15 from "./components/ProductShelf.tsx";
import * as $$$16 from "./components/QuantitySelector.tsx";
import * as $$$17 from "./components/Search.tsx";
import * as $$$18 from "./components/StoreFeatures.tsx";
import * as $$$19 from "./components/icons/AmeIcon.tsx";
import * as $$$20 from "./components/icons/AmericanExpressIcon.tsx";
import * as $$$21 from "./components/icons/BoletoIcon.tsx";
import * as $$$22 from "./components/icons/CartIcon.tsx";
import * as $$$23 from "./components/icons/ChatIcon.tsx";
import * as $$$24 from "./components/icons/CloseIcon.tsx";
import * as $$$25 from "./components/icons/DecoFashionLogo.tsx";
import * as $$$26 from "./components/icons/EloIcon.tsx";
import * as $$$27 from "./components/icons/EmailIcon.tsx";
import * as $$$28 from "./components/icons/FacebookIcon.tsx";
import * as $$$29 from "./components/icons/HeartIcon.tsx";
import * as $$$30 from "./components/icons/InstagramIcon.tsx";
import * as $$$31 from "./components/icons/LeftArrow.tsx";
import * as $$$32 from "./components/icons/LogoZeeDog.tsx";
import * as $$$33 from "./components/icons/MagnifyingGlassIcon.tsx";
import * as $$$34 from "./components/icons/MastercardIcon.tsx";
import * as $$$35 from "./components/icons/MenuIcon.tsx";
import * as $$$36 from "./components/icons/PercentageCircle.tsx";
import * as $$$37 from "./components/icons/PersonIcon.tsx";
import * as $$$38 from "./components/icons/PicpayIcon.tsx";
import * as $$$39 from "./components/icons/PixIcon.tsx";
import * as $$$40 from "./components/icons/SearchIcon.tsx";
import * as $$$41 from "./components/icons/SpotifyIcon.tsx";
import * as $$$42 from "./components/icons/TimeLapseIcon.tsx";
import * as $$$43 from "./components/icons/TruckIcon.tsx";
import * as $$$44 from "./components/icons/TwitterIcon.tsx";
import * as $$$45 from "./components/icons/UserIcon.tsx";
import * as $$$46 from "./components/icons/VisaIcon.tsx";
import * as $$$47 from "./components/icons/WhatsappIcon.tsx";
import * as $$$48 from "./components/icons/YoutubeIcon.tsx";
import * as $$$49 from "./components/icons/ZeecatLogo.tsx";
import * as $$$50 from "./components/icons/ZeedogConnectsLogo.tsx";
import * as $$$51 from "./components/icons/ZeenowLogo.tsx";
import * as $$$52 from "./components/ui/Image.tsx";
import * as $$$53 from "./components/ui/Spinner.tsx";
import * as $$$54 from "./components/ui/Video.tsx";
import * as $$$$0 from "./loaders/vtex/searchCollections.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/[slug]/p.tsx": $1,
    "./routes/admin.tsx": $2,
    "./routes/api/cart/index.ts": $3,
    "./routes/api/cart/items.ts": $4,
    "./routes/cart.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/inspect-vscode.ts": $7,
    "./routes/live/login.tsx": $8,
    "./routes/live/login/success.tsx": $9,
    "./routes/search.tsx": $10,
    "./routes/start.tsx": $11,
  },
  islands: {
    "./islands/AddToCart.tsx": $$0,
    "./islands/Alert.tsx": $$1,
    "./islands/AuthListener.tsx": $$2,
    "./islands/Editor.tsx": $$3,
    "./islands/InspectVSCode.tsx": $$4,
    "./islands/LoginButtons.tsx": $$5,
    "./islands/Minicart.tsx": $$6,
    "./islands/ProductInformation.tsx": $$7,
    "./islands/SearchBar.tsx": $$8,
    "./islands/SearchControls.tsx": $$9,
    "./islands/VideoCarousel.tsx": $$10,
  },
  components: {
    "./components/Banner.tsx": $$$0,
    "./components/BannerGridImages.tsx": $$$1,
    "./components/BannerImg.tsx": $$$2,
    "./components/Footer.tsx": $$$3,
    "./components/GetStarted.tsx": $$$4,
    "./components/Head.tsx": $$$5,
    "./components/Header.tsx": $$$6,
    "./components/HomeFilter.tsx": $$$7,
    "./components/IconCart.tsx": $$$8,
    "./components/ListLinks.tsx": $$$9,
    "./components/MarcasConvidadas.tsx": $$$10,
    "./components/Newsletter.tsx": $$$11,
    "./components/ProductCard.tsx": $$$12,
    "./components/ProductDetails.tsx": $$$13,
    "./components/ProductGallery.tsx": $$$14,
    "./components/ProductShelf.tsx": $$$15,
    "./components/QuantitySelector.tsx": $$$16,
    "./components/Search.tsx": $$$17,
    "./components/StoreFeatures.tsx": $$$18,
    "./components/icons/AmeIcon.tsx": $$$19,
    "./components/icons/AmericanExpressIcon.tsx": $$$20,
    "./components/icons/BoletoIcon.tsx": $$$21,
    "./components/icons/CartIcon.tsx": $$$22,
    "./components/icons/ChatIcon.tsx": $$$23,
    "./components/icons/CloseIcon.tsx": $$$24,
    "./components/icons/DecoFashionLogo.tsx": $$$25,
    "./components/icons/EloIcon.tsx": $$$26,
    "./components/icons/EmailIcon.tsx": $$$27,
    "./components/icons/FacebookIcon.tsx": $$$28,
    "./components/icons/HeartIcon.tsx": $$$29,
    "./components/icons/InstagramIcon.tsx": $$$30,
    "./components/icons/LeftArrow.tsx": $$$31,
    "./components/icons/LogoZeeDog.tsx": $$$32,
    "./components/icons/MagnifyingGlassIcon.tsx": $$$33,
    "./components/icons/MastercardIcon.tsx": $$$34,
    "./components/icons/MenuIcon.tsx": $$$35,
    "./components/icons/PercentageCircle.tsx": $$$36,
    "./components/icons/PersonIcon.tsx": $$$37,
    "./components/icons/PicpayIcon.tsx": $$$38,
    "./components/icons/PixIcon.tsx": $$$39,
    "./components/icons/SearchIcon.tsx": $$$40,
    "./components/icons/SpotifyIcon.tsx": $$$41,
    "./components/icons/TimeLapseIcon.tsx": $$$42,
    "./components/icons/TruckIcon.tsx": $$$43,
    "./components/icons/TwitterIcon.tsx": $$$44,
    "./components/icons/UserIcon.tsx": $$$45,
    "./components/icons/VisaIcon.tsx": $$$46,
    "./components/icons/WhatsappIcon.tsx": $$$47,
    "./components/icons/YoutubeIcon.tsx": $$$48,
    "./components/icons/ZeecatLogo.tsx": $$$49,
    "./components/icons/ZeedogConnectsLogo.tsx": $$$50,
    "./components/icons/ZeenowLogo.tsx": $$$51,
    "./components/ui/Image.tsx": $$$52,
    "./components/ui/Spinner.tsx": $$$53,
    "./components/ui/Video.tsx": $$$54,
  },
  loaders: { "./loaders/vtex/searchCollections.ts": $$$$0 },
  schemas: {
    "SearchControls": {
      "title": "SearchControls",
      "type": "object",
      "properties": {},
    },
    "VideoCarousel": {
      "title": "Carousel de Vídeos",
      "type": "object",
      "required": ["video1"],
      "properties": {
        "video1": {
          "type": "object",
          "properties": {
            "mobile": { "type": "string", "title": "Vídeo Mobile" },
            "desktop": { "type": "string", "title": "Vídeo Desktop" },
            "alt": { "type": "string", "title": "Texto alternativo" },
            "link": { "type": "string", "title": "Link" },
          },
        },
        "video2": {
          "type": "object",
          "properties": {
            "mobile": { "type": "string", "title": "Vídeo Mobile" },
            "desktop": { "type": "string", "title": "Vídeo Desktop" },
            "alt": { "type": "string", "title": "Texto alternativo" },
            "link": { "type": "string", "title": "Link" },
          },
        },
        "video3": {
          "type": "object",
          "properties": {
            "mobile": { "type": "string", "title": "Vídeo Mobile" },
            "desktop": { "type": "string", "title": "Vídeo Desktop" },
            "alt": { "type": "string", "title": "Texto alternativo" },
            "link": { "type": "string", "title": "Link" },
          },
        },
      },
    },
    "Banner": {
      "title": "Main Banner",
      "type": "object",
      "required": ["imgSrc", "bannerTexts"],
      "properties": {
        "imgSrc": {
          "type": "object",
          "properties": {
            "mobile": {
              "type": "string",
              "title": "Imagem Mobile",
              "format": "uri",
            },
            "desktop": {
              "type": "string",
              "title": "Imagem Desktop",
              "format": "uri",
            },
          },
        },
        "alt": { "type": "string", "title": "alternate" },
        "text": { "type": "string", "title": "Primeiro texto" },
        "title": { "type": "string", "title": "Título" },
        "subtitle": { "type": "string", "title": "Subtítulo" },
        "CTA": { "type": "string", "title": "Texto CTA do link" },
        "link": { "type": "string", "title": "Link" },
      },
    },
    "BannerGridImages": {
      "title": "Banner Grid",
      "type": "object",
      "required": ["title"],
      "properties": {
        "title": { "type": "string", "title": "Título do grid" },
        "imgBanner1": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
        "imgBanner2": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
        "imgBanner3": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
        "imgBanner4": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
        "imgBanner5": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
        "imgBanner6": {
          "type": "object",
          "properties": {
            "desktop": { "type": "string", "title": "Imagem", "format": "uri" },
            "alt": { "type": "string", "title": "alternate" },
            "link": { "type": "string", "title": "Link da imagem" },
          },
        },
      },
    },
    "BannerImg": {
      "title": "Banner Imagem",
      "type": "object",
      "required": ["imgSrc", "bannerTexts"],
      "properties": {
        "imgSrc": {
          "type": "object",
          "properties": {
            "mobile": {
              "type": "string",
              "title": "Imagem Mobile",
              "format": "uri",
            },
            "desktop": {
              "type": "string",
              "title": "Imagem Desktop",
              "format": "uri",
            },
          },
        },
        "alt": { "type": "string", "title": "alternate" },
        "textColor": { "type": "string", "title": "Cor do texto" },
        "text": { "type": "string", "title": "Primeiro texto" },
        "title": { "type": "string", "title": "Título" },
        "subtitle": { "type": "string", "title": "Subtítulo" },
        "link": { "type": "string", "title": "Link vinculado ao CTA" },
        "CTA": { "type": "string", "title": "Texto do CTA" },
      },
    },
    "Footer": {
      "title": "Footer",
      "type": "object",
      "properties": {
        "paragraph1": { "type": "string", "title": "Título 1" },
        "menuitem1": { "type": "string", "title": "Menu Item 1" },
        "menuitem2": { "type": "string", "title": "Menu Item 2" },
        "menuitem3": { "type": "string", "title": "Menu Item 3" },
        "menuitem4": { "type": "string", "title": "Menu Item 4" },
        "menuitem5": { "type": "string", "title": "Menu Item 5" },
        "menuitem6": { "type": "string", "title": "Menu Item 6" },
        "menuitem7": { "type": "string", "title": "Menu Item 7" },
        "menuitem8": { "type": "string", "title": "Menu Item 8" },
        "menuitem9": { "type": "string", "title": "Menu Item 9" },
        "menuitem10": { "type": "string", "title": "Menu Item 10" },
        "paragraph2": { "type": "string", "title": "Título 2" },
        "menuitem11": { "type": "string", "title": "Menu Item 11" },
        "menuitem12": { "type": "string", "title": "Menu Item 12" },
        "menuitem13": { "type": "string", "title": "Menu Item 13" },
        "menuitem14": { "type": "string", "title": "Menu Item 14" },
        "menuitem15": { "type": "string", "title": "Menu Item 15" },
        "menuitem16": { "type": "string", "title": "Menu Item 16" },
        "paragraph3": { "type": "string", "title": "Título 3" },
        "menuitem17": { "type": "string", "title": "Menu Item 17" },
        "menuitem18": { "type": "string", "title": "Menu Item 18" },
        "menuitem19": { "type": "string", "title": "Menu Item 19" },
        "paragraph4": { "type": "string", "title": "Título 4" },
        "paragraph5": { "type": "string", "title": "Título 5" },
        "paragraph6": { "type": "string", "title": "Título 6" },
      },
    },
    "Head": {
      "type": "object",
      "properties": {
        "title": { "title": "Título da Página", "type": "string" },
        "description": { "title": "Descrição", "type": "string" },
        "faviconUrl": { "title": "Favicon URL", "type": "string" },
        "url": { "title": "URL", "type": "string" },
      },
      "required": ["description", "faviconUrl", "title", "url"],
      "title": "Head (SEO)",
    },
    "Header": { "title": "Header", "type": "object", "properties": {} },
    "HomeFilter": { "title": "HomeFilter", "type": "object", "properties": {} },
    "MarcasConvidadas": {
      "title": "Marcas Convidadas",
      "type": "object",
      "properties": {},
    },
    "Newsletter": { "title": "Newsletter", "type": "object", "properties": {} },
    "ProductDetails": {
      "title": "Product Details",
      "type": "object",
      "properties": { "products": { "$ref": "searchCollections" } },
    },
    "ProductGallery": {
      "title": "Product Gallery",
      "type": "object",
      "required": ["collection"],
      "properties": {
        "products": {
          "$ref": "searchCollections",
          "type": "object",
          "title": "Products",
          "properties": {
            "collection": { "type": "string", "title": "Coleção" },
            "count": { "type": "number", "title": "Num. de itens" },
          },
        },
      },
    },
    "ProductShelf": {
      "title": "Product Shelf",
      "type": "object",
      "required": ["title", "collection"],
      "properties": {
        "title": { "type": "string", "title": "Título" },
        "products": {
          "$ref": "searchCollections",
          "type": "object",
          "title": "Products",
          "properties": {
            "collection": { "type": "string", "title": "Coleção" },
            "count": { "type": "number", "title": "Num. de itens" },
          },
        },
      },
    },
    "StoreFeatures": {
      "title": "StoreFeatures",
      "type": "object",
      "properties": {},
    },
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
