// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$0 from "./routes/_app.tsx";
import * as $$$$$0 from "./islands/Newsletter.tsx";
import * as $$$$$1 from "./islands/WishlistButton.tsx";
import * as $$$$$2 from "./islands/ShippingSimulation.tsx";
import * as $$$$$3 from "./islands/AddToCartButton.tsx";
import * as $$$$$4 from "./islands/SliderJS.tsx";
import * as $$$$$5 from "./islands/ProductImageZoom.tsx";
import * as $$$$$6 from "./islands/OutOfStock.tsx";
import * as $$$$$7 from "./islands/Header/Drawers.tsx";
import * as $$$$$8 from "./islands/Header/Searchbar.tsx";
import * as $$$$$9 from "./islands/Header/Buttons.tsx";
import * as $$$$$10 from "./islands/SearchControls.tsx";
import * as $$$$$$$$0 from "./sections/Footer/Footer.tsx";
import * as $$$$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$$$2 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$$$3 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$$$4 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$$$5 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$$$6 from "./sections/Images/Carousel.tsx";
import * as $$$$$$$$7 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$$$8 from "./sections/Content/Logos.tsx";
import * as $$$$$$$$9 from "./sections/Content/Faq.tsx";
import * as $$$$$$$$10 from "./sections/Content/Benefits.tsx";
import * as $$$$$$$$11 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$$$12 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$$$13 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$$$14 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$$$15 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$$$16 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$$$17 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$$$18 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$$$19 from "./sections/Theme/Theme.tsx";
import * as $$$$$$$$20 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$$$21 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$$$22 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$$$23 from "./sections/Header/Header.tsx";
import { DecoManifest } from "$live/types.ts";
import * as i2$$$0 from "$live/loaders/secret.ts";
import * as i2$$$1 from "$live/loaders/state.ts";
import * as i2$$$2 from "$live/loaders/workflows/events.ts";
import * as i2$$$3 from "$live/loaders/workflows/get.ts";
import * as i2$$$$0 from "$live/handlers/devPage.ts";
import * as i2$$$$1 from "$live/handlers/fresh.ts";
import * as i2$$$$2 from "$live/handlers/proxy.ts";
import * as i2$$$$3 from "$live/handlers/redirect.ts";
import * as i2$$$$4 from "$live/handlers/router.ts";
import * as i2$$$$5 from "$live/handlers/routesSelection.ts";
import * as i2$$$$6 from "$live/handlers/workflowRunner.ts";
import * as i2$$$$$$$0 from "$live/pages/LivePage.tsx";
import * as i2$$$$$0 from "$live/sections/Conditional_Beta.tsx";
import * as i2$$$$$1 from "$live/sections/EmptySection.tsx";
import * as i2$$$$$2 from "$live/sections/PageInclude.tsx";
import * as i2$$$$$3 from "$live/sections/Slot.tsx";
import * as i2$$$$$4 from "$live/sections/UseSlot.tsx";
import * as i2$$$$$$$$0 from "$live/matchers/MatchAlways.ts";
import * as i2$$$$$$$$1 from "$live/matchers/MatchCron.ts";
import * as i2$$$$$$$$2 from "$live/matchers/MatchDate.ts";
import * as i2$$$$$$$$3 from "$live/matchers/MatchDevice.ts";
import * as i2$$$$$$$$4 from "$live/matchers/MatchEnvironment.ts";
import * as i2$$$$$$$$5 from "$live/matchers/MatchHost.ts";
import * as i2$$$$$$$$6 from "$live/matchers/MatchLocation.ts";
import * as i2$$$$$$$$7 from "$live/matchers/MatchMulti.ts";
import * as i2$$$$$$$$8 from "$live/matchers/MatchRandom.ts";
import * as i2$$$$$$$$9 from "$live/matchers/MatchSite.ts";
import * as i2$$$$$$$$10 from "$live/matchers/MatchUserAgent.ts";
import * as i2$$$$$$$$$0 from "$live/flags/audience.ts";
import * as i2$$$$$$$$$1 from "$live/flags/everyone.ts";
import * as i2$$$$$$$$$2 from "$live/flags/flag.ts";
import * as i2$$$$$$$$$3 from "$live/flags/multivariate.ts";
import * as i2$$$$$$0 from "$live/actions/secrets/encrypt.ts";
import * as i2$$$$$$1 from "$live/actions/workflows/cancel.ts";
import * as i2$$$$$$2 from "$live/actions/workflows/signal.ts";
import * as i2$$$$$$3 from "$live/actions/workflows/start.ts";
import * as i2$0 from "deco-sites/std/functions/butterCMSAds.ts";
import * as i2$1 from "deco-sites/std/functions/butterCMSBrands.ts";
import * as i2$2 from "deco-sites/std/functions/butterCMSCategories.ts";
import * as i2$3 from "deco-sites/std/functions/butterCMSFeaturedPosts.ts";
import * as i2$4 from "deco-sites/std/functions/butterCMSPage.ts";
import * as i2$5 from "deco-sites/std/functions/butterCMSPlaces.ts";
import * as i2$6 from "deco-sites/std/functions/butterCMSPostDetail.ts";
import * as i2$7 from "deco-sites/std/functions/butterCMSPosts.ts";
import * as i2$8 from "deco-sites/std/functions/butterCMSRelatedPosts.ts";
import * as i2$9 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as i2$10 from "deco-sites/std/functions/requestToParam.ts";
import * as i2$11 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as i2$12 from "deco-sites/std/functions/shopifyProductList.ts";
import * as i2$13 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as i2$14 from "deco-sites/std/functions/vndaProductDetailsPage.ts";
import * as i2$15 from "deco-sites/std/functions/vndaProductList.ts";
import * as i2$16 from "deco-sites/std/functions/vndaProductListingPage.ts";
import * as i2$17 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as i2$18 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as i2$19 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as i2$20 from "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts";
import * as i2$21 from "deco-sites/std/functions/vtexNavbar.ts";
import * as i2$22 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as i2$23 from "deco-sites/std/functions/vtexProductList.ts";
import * as i2$24 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as i2$25 from "deco-sites/std/functions/vtexSuggestions.ts";
import * as i2$26 from "deco-sites/std/functions/vtexWishlist.ts";
import * as i2$$0 from "deco-sites/std/accounts/butterCMS.ts";
import * as i2$$1 from "deco-sites/std/accounts/linxImpulse.ts";
import * as i2$$2 from "deco-sites/std/accounts/nuvemShop.ts";
import * as i2$$3 from "deco-sites/std/accounts/occ.ts";
import * as i2$$4 from "deco-sites/std/accounts/shopify.ts";
import * as i2$$5 from "deco-sites/std/accounts/vnda.ts";
import * as i2$$6 from "deco-sites/std/accounts/vtex.ts";
import * as i2$$7 from "deco-sites/std/accounts/yourViews.ts";
import * as i2$$$4 from "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts";
import * as i2$$$5 from "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts";
import * as i2$$$6 from "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts";
import * as i2$$$7 from "deco-sites/std/loaders/linxImpulse/products/similarItems.ts";
import * as i2$$$8 from "deco-sites/std/loaders/linxImpulse/search.ts";
import * as i2$$$9 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts";
import * as i2$$$10 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts";
import * as i2$$$11 from "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts";
import * as i2$$$12 from "deco-sites/std/loaders/vnda/cart.ts";
import * as i2$$$13 from "deco-sites/std/loaders/vnda/productDetailsPage.ts";
import * as i2$$$14 from "deco-sites/std/loaders/vnda/productList.ts";
import * as i2$$$15 from "deco-sites/std/loaders/vnda/productListingPage.ts";
import * as i2$$$16 from "deco-sites/std/loaders/vnda/proxy.ts";
import * as i2$$$17 from "deco-sites/std/loaders/vtex/cart.ts";
import * as i2$$$18 from "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts";
import * as i2$$$19 from "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts";
import * as i2$$$20 from "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts";
import * as i2$$$21 from "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts";
import * as i2$$$22 from "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts";
import * as i2$$$23 from "deco-sites/std/loaders/vtex/legacy/productList.ts";
import * as i2$$$24 from "deco-sites/std/loaders/vtex/legacy/productListingPage.ts";
import * as i2$$$25 from "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts";
import * as i2$$$26 from "deco-sites/std/loaders/vtex/navbar.ts";
import * as i2$$$27 from "deco-sites/std/loaders/vtex/proxy.ts";
import * as i2$$$28 from "deco-sites/std/loaders/vtex/user.ts";
import * as i2$$$29 from "deco-sites/std/loaders/vtex/wishlist.ts";
import * as i2$$$30 from "deco-sites/std/loaders/x/font.ts";
import * as i2$$$31 from "deco-sites/std/loaders/x/image.ts";
import * as i2$$$32 from "deco-sites/std/loaders/x/redirectsFromCsv.ts";
import * as i2$$$$7 from "deco-sites/std/handlers/sitemap.ts";
import * as i2$$$$8 from "deco-sites/std/handlers/vtex/sitemap.ts";
import * as i2$$$$$5 from "deco-sites/std/sections/Analytics.tsx";
import * as i2$$$$$6 from "deco-sites/std/sections/configButterCMS.global.tsx";
import * as i2$$$$$7 from "deco-sites/std/sections/configLinxImpulse.global.tsx";
import * as i2$$$$$8 from "deco-sites/std/sections/configNuvemShop.tsx";
import * as i2$$$$$9 from "deco-sites/std/sections/configOCC.global.tsx";
import * as i2$$$$$10 from "deco-sites/std/sections/configShopify.global.tsx";
import * as i2$$$$$11 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as i2$$$$$12 from "deco-sites/std/sections/configYourViews.global.tsx";
import * as i2$$$$$13 from "deco-sites/std/sections/SEO.tsx";
import * as i2$$$$$14 from "deco-sites/std/sections/SEOPDP.tsx";
import * as i2$$$$$15 from "deco-sites/std/sections/SEOPLP.tsx";
import * as i2$$$$$16 from "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx";
import * as i2$$$$$$4 from "deco-sites/std/actions/vnda/cart/addItem.ts";
import * as i2$$$$$$5 from "deco-sites/std/actions/vnda/cart/setShippingAddress.ts";
import * as i2$$$$$$6 from "deco-sites/std/actions/vnda/cart/updateCoupon.ts";
import * as i2$$$$$$7 from "deco-sites/std/actions/vnda/cart/updateItem.ts";
import * as i2$$$$$$8 from "deco-sites/std/actions/vtex/analytics/sendEvent.ts";
import * as i2$$$$$$9 from "deco-sites/std/actions/vtex/cart/addItems.ts";
import * as i2$$$$$$10 from "deco-sites/std/actions/vtex/cart/getInstallment.ts";
import * as i2$$$$$$11 from "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts";
import * as i2$$$$$$12 from "deco-sites/std/actions/vtex/cart/removeItems.ts";
import * as i2$$$$$$13 from "deco-sites/std/actions/vtex/cart/simulation.ts";
import * as i2$$$$$$14 from "deco-sites/std/actions/vtex/cart/updateAttachment.ts";
import * as i2$$$$$$15 from "deco-sites/std/actions/vtex/cart/updateCoupons.ts";
import * as i2$$$$$$16 from "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts";
import * as i2$$$$$$17 from "deco-sites/std/actions/vtex/cart/updateItemPrice.ts";
import * as i2$$$$$$18 from "deco-sites/std/actions/vtex/cart/updateItems.ts";
import * as i2$$$$$$19 from "deco-sites/std/actions/vtex/cart/updateProfile.ts";
import * as i2$$$$$$20 from "deco-sites/std/actions/vtex/cart/updateUser.ts";
import * as i2$$$$$$21 from "deco-sites/std/actions/vtex/newsletter/subscribe.ts";
import * as i2$$$$$$22 from "deco-sites/std/actions/vtex/notifyme.ts";
import * as i2$$$$$$23 from "deco-sites/std/actions/vtex/wishlist/addItem.ts";
import * as i2$$$$$$24 from "deco-sites/std/actions/vtex/wishlist/removeItem.ts";

const manifest = {
  "routes": {
    "./routes/_app.tsx": $$$$0,
  },
  "islands": {
    "./islands/AddToCartButton.tsx": $$$$$3,
    "./islands/Header/Buttons.tsx": $$$$$9,
    "./islands/Header/Drawers.tsx": $$$$$7,
    "./islands/Header/Searchbar.tsx": $$$$$8,
    "./islands/Newsletter.tsx": $$$$$0,
    "./islands/OutOfStock.tsx": $$$$$6,
    "./islands/ProductImageZoom.tsx": $$$$$5,
    "./islands/SearchControls.tsx": $$$$$10,
    "./islands/ShippingSimulation.tsx": $$$$$2,
    "./islands/SliderJS.tsx": $$$$$4,
    "./islands/WishlistButton.tsx": $$$$$1,
  },
  "sections": {
    "$live/sections/Conditional_Beta.tsx": i2$$$$$0,
    "$live/sections/EmptySection.tsx": i2$$$$$1,
    "$live/sections/PageInclude.tsx": i2$$$$$2,
    "$live/sections/Slot.tsx": i2$$$$$3,
    "$live/sections/UseSlot.tsx": i2$$$$$4,
    "deco-sites/fashion/sections/Category/CategoryBanner.tsx": $$$$$$$$1,
    "deco-sites/fashion/sections/Category/CategoryList.tsx": $$$$$$$$2,
    "deco-sites/fashion/sections/Content/Benefits.tsx": $$$$$$$$10,
    "deco-sites/fashion/sections/Content/Faq.tsx": $$$$$$$$9,
    "deco-sites/fashion/sections/Content/Logos.tsx": $$$$$$$$8,
    "deco-sites/fashion/sections/Content/Testimonials.tsx": $$$$$$$$7,
    "deco-sites/fashion/sections/Footer/Footer.tsx": $$$$$$$$0,
    "deco-sites/fashion/sections/Header/Header.tsx": $$$$$$$$23,
    "deco-sites/fashion/sections/Images/BannerGrid.tsx": $$$$$$$$4,
    "deco-sites/fashion/sections/Images/Carousel.tsx": $$$$$$$$6,
    "deco-sites/fashion/sections/Images/ImageGallery.tsx": $$$$$$$$5,
    "deco-sites/fashion/sections/Images/ShoppableBanner.tsx": $$$$$$$$3,
    "deco-sites/fashion/sections/Links/LinkTree.tsx": $$$$$$$$20,
    "deco-sites/fashion/sections/Links/Shortcuts.tsx": $$$$$$$$21,
    "deco-sites/fashion/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$$$15,
    "deco-sites/fashion/sections/Miscellaneous/CookieConsent.tsx": $$$$$$$$16,
    "deco-sites/fashion/sections/Newsletter/Newsletter.tsx": $$$$$$$$22,
    "deco-sites/fashion/sections/Product/ProductDetails.tsx": $$$$$$$$14,
    "deco-sites/fashion/sections/Product/ProductShelf.tsx": $$$$$$$$13,
    "deco-sites/fashion/sections/Product/SearchResult.tsx": $$$$$$$$12,
    "deco-sites/fashion/sections/Product/Wishlist.tsx": $$$$$$$$11,
    "deco-sites/fashion/sections/Social/InstagramPosts.tsx": $$$$$$$$18,
    "deco-sites/fashion/sections/Social/WhatsApp.tsx": $$$$$$$$17,
    "deco-sites/fashion/sections/Theme/Theme.tsx": $$$$$$$$19,
    "deco-sites/std/sections/Analytics.tsx": i2$$$$$5,
    "deco-sites/std/sections/configButterCMS.global.tsx": i2$$$$$6,
    "deco-sites/std/sections/configLinxImpulse.global.tsx": i2$$$$$7,
    "deco-sites/std/sections/configNuvemShop.tsx": i2$$$$$8,
    "deco-sites/std/sections/configOCC.global.tsx": i2$$$$$9,
    "deco-sites/std/sections/configShopify.global.tsx": i2$$$$$10,
    "deco-sites/std/sections/configVTEX.global.tsx": i2$$$$$11,
    "deco-sites/std/sections/configYourViews.global.tsx": i2$$$$$12,
    "deco-sites/std/sections/SEO.tsx": i2$$$$$13,
    "deco-sites/std/sections/SEOPDP.tsx": i2$$$$$14,
    "deco-sites/std/sections/SEOPLP.tsx": i2$$$$$15,
    "deco-sites/std/sections/VTEXPortalDataLayerCompatibility.tsx": i2$$$$$16,
  },
  "loaders": {
    "$live/loaders/secret.ts": i2$$$0,
    "$live/loaders/state.ts": i2$$$1,
    "$live/loaders/workflows/events.ts": i2$$$2,
    "$live/loaders/workflows/get.ts": i2$$$3,
    "deco-sites/std/loaders/linxImpulse/autocompletes/popular.ts": i2$$$4,
    "deco-sites/std/loaders/linxImpulse/autocompletes/suggestions.ts": i2$$$5,
    "deco-sites/std/loaders/linxImpulse/pages/recommendations.ts": i2$$$6,
    "deco-sites/std/loaders/linxImpulse/products/similarItems.ts": i2$$$7,
    "deco-sites/std/loaders/linxImpulse/search.ts": i2$$$8,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductDetailsPage.ts": i2$$$9,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductList.ts": i2$$$10,
    "deco-sites/std/loaders/nuvemShop/nuvemShopProductListingPage.ts": i2$$$11,
    "deco-sites/std/loaders/vnda/cart.ts": i2$$$12,
    "deco-sites/std/loaders/vnda/productDetailsPage.ts": i2$$$13,
    "deco-sites/std/loaders/vnda/productList.ts": i2$$$14,
    "deco-sites/std/loaders/vnda/productListingPage.ts": i2$$$15,
    "deco-sites/std/loaders/vnda/proxy.ts": i2$$$16,
    "deco-sites/std/loaders/vtex/cart.ts": i2$$$17,
    "deco-sites/std/loaders/vtex/intelligentSearch/productDetailsPage.ts":
      i2$$$18,
    "deco-sites/std/loaders/vtex/intelligentSearch/productList.ts": i2$$$19,
    "deco-sites/std/loaders/vtex/intelligentSearch/productListingPage.ts":
      i2$$$20,
    "deco-sites/std/loaders/vtex/intelligentSearch/suggestions.ts": i2$$$21,
    "deco-sites/std/loaders/vtex/legacy/productDetailsPage.ts": i2$$$22,
    "deco-sites/std/loaders/vtex/legacy/productList.ts": i2$$$23,
    "deco-sites/std/loaders/vtex/legacy/productListingPage.ts": i2$$$24,
    "deco-sites/std/loaders/vtex/legacy/relatedProductsLoader.ts": i2$$$25,
    "deco-sites/std/loaders/vtex/navbar.ts": i2$$$26,
    "deco-sites/std/loaders/vtex/proxy.ts": i2$$$27,
    "deco-sites/std/loaders/vtex/user.ts": i2$$$28,
    "deco-sites/std/loaders/vtex/wishlist.ts": i2$$$29,
    "deco-sites/std/loaders/x/font.ts": i2$$$30,
    "deco-sites/std/loaders/x/image.ts": i2$$$31,
    "deco-sites/std/loaders/x/redirectsFromCsv.ts": i2$$$32,
  },
  "handlers": {
    "$live/handlers/devPage.ts": i2$$$$0,
    "$live/handlers/fresh.ts": i2$$$$1,
    "$live/handlers/proxy.ts": i2$$$$2,
    "$live/handlers/redirect.ts": i2$$$$3,
    "$live/handlers/router.ts": i2$$$$4,
    "$live/handlers/routesSelection.ts": i2$$$$5,
    "$live/handlers/workflowRunner.ts": i2$$$$6,
    "deco-sites/std/handlers/sitemap.ts": i2$$$$7,
    "deco-sites/std/handlers/vtex/sitemap.ts": i2$$$$8,
  },
  "pages": {
    "$live/pages/LivePage.tsx": i2$$$$$$$0,
  },
  "matchers": {
    "$live/matchers/MatchAlways.ts": i2$$$$$$$$0,
    "$live/matchers/MatchCron.ts": i2$$$$$$$$1,
    "$live/matchers/MatchDate.ts": i2$$$$$$$$2,
    "$live/matchers/MatchDevice.ts": i2$$$$$$$$3,
    "$live/matchers/MatchEnvironment.ts": i2$$$$$$$$4,
    "$live/matchers/MatchHost.ts": i2$$$$$$$$5,
    "$live/matchers/MatchLocation.ts": i2$$$$$$$$6,
    "$live/matchers/MatchMulti.ts": i2$$$$$$$$7,
    "$live/matchers/MatchRandom.ts": i2$$$$$$$$8,
    "$live/matchers/MatchSite.ts": i2$$$$$$$$9,
    "$live/matchers/MatchUserAgent.ts": i2$$$$$$$$10,
  },
  "flags": {
    "$live/flags/audience.ts": i2$$$$$$$$$0,
    "$live/flags/everyone.ts": i2$$$$$$$$$1,
    "$live/flags/flag.ts": i2$$$$$$$$$2,
    "$live/flags/multivariate.ts": i2$$$$$$$$$3,
  },
  "actions": {
    "$live/actions/secrets/encrypt.ts": i2$$$$$$0,
    "$live/actions/workflows/cancel.ts": i2$$$$$$1,
    "$live/actions/workflows/signal.ts": i2$$$$$$2,
    "$live/actions/workflows/start.ts": i2$$$$$$3,
    "deco-sites/std/actions/vnda/cart/addItem.ts": i2$$$$$$4,
    "deco-sites/std/actions/vnda/cart/setShippingAddress.ts": i2$$$$$$5,
    "deco-sites/std/actions/vnda/cart/updateCoupon.ts": i2$$$$$$6,
    "deco-sites/std/actions/vnda/cart/updateItem.ts": i2$$$$$$7,
    "deco-sites/std/actions/vtex/analytics/sendEvent.ts": i2$$$$$$8,
    "deco-sites/std/actions/vtex/cart/addItems.ts": i2$$$$$$9,
    "deco-sites/std/actions/vtex/cart/getInstallment.ts": i2$$$$$$10,
    "deco-sites/std/actions/vtex/cart/removeItemAttachment.ts": i2$$$$$$11,
    "deco-sites/std/actions/vtex/cart/removeItems.ts": i2$$$$$$12,
    "deco-sites/std/actions/vtex/cart/simulation.ts": i2$$$$$$13,
    "deco-sites/std/actions/vtex/cart/updateAttachment.ts": i2$$$$$$14,
    "deco-sites/std/actions/vtex/cart/updateCoupons.ts": i2$$$$$$15,
    "deco-sites/std/actions/vtex/cart/updateItemAttachment.ts": i2$$$$$$16,
    "deco-sites/std/actions/vtex/cart/updateItemPrice.ts": i2$$$$$$17,
    "deco-sites/std/actions/vtex/cart/updateItems.ts": i2$$$$$$18,
    "deco-sites/std/actions/vtex/cart/updateProfile.ts": i2$$$$$$19,
    "deco-sites/std/actions/vtex/cart/updateUser.ts": i2$$$$$$20,
    "deco-sites/std/actions/vtex/newsletter/subscribe.ts": i2$$$$$$21,
    "deco-sites/std/actions/vtex/notifyme.ts": i2$$$$$$22,
    "deco-sites/std/actions/vtex/wishlist/addItem.ts": i2$$$$$$23,
    "deco-sites/std/actions/vtex/wishlist/removeItem.ts": i2$$$$$$24,
  },
  "functions": {
    "deco-sites/std/functions/butterCMSAds.ts": i2$0,
    "deco-sites/std/functions/butterCMSBrands.ts": i2$1,
    "deco-sites/std/functions/butterCMSCategories.ts": i2$2,
    "deco-sites/std/functions/butterCMSFeaturedPosts.ts": i2$3,
    "deco-sites/std/functions/butterCMSPage.ts": i2$4,
    "deco-sites/std/functions/butterCMSPlaces.ts": i2$5,
    "deco-sites/std/functions/butterCMSPostDetail.ts": i2$6,
    "deco-sites/std/functions/butterCMSPosts.ts": i2$7,
    "deco-sites/std/functions/butterCMSRelatedPosts.ts": i2$8,
    "deco-sites/std/functions/occProductDetailsPage.ts": i2$9,
    "deco-sites/std/functions/requestToParam.ts": i2$10,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": i2$11,
    "deco-sites/std/functions/shopifyProductList.ts": i2$12,
    "deco-sites/std/functions/shopifyProductListingPage.ts": i2$13,
    "deco-sites/std/functions/vndaProductDetailsPage.ts": i2$14,
    "deco-sites/std/functions/vndaProductList.ts": i2$15,
    "deco-sites/std/functions/vndaProductListingPage.ts": i2$16,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": i2$17,
    "deco-sites/std/functions/vtexLegacyProductList.ts": i2$18,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": i2$19,
    "deco-sites/std/functions/vtexLegacyRelatedProductsLoader.ts": i2$20,
    "deco-sites/std/functions/vtexNavbar.ts": i2$21,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": i2$22,
    "deco-sites/std/functions/vtexProductList.ts": i2$23,
    "deco-sites/std/functions/vtexProductListingPage.ts": i2$24,
    "deco-sites/std/functions/vtexSuggestions.ts": i2$25,
    "deco-sites/std/functions/vtexWishlist.ts": i2$26,
  },
  "accounts": {
    "deco-sites/std/accounts/butterCMS.ts": i2$$0,
    "deco-sites/std/accounts/linxImpulse.ts": i2$$1,
    "deco-sites/std/accounts/nuvemShop.ts": i2$$2,
    "deco-sites/std/accounts/occ.ts": i2$$3,
    "deco-sites/std/accounts/shopify.ts": i2$$4,
    "deco-sites/std/accounts/vnda.ts": i2$$5,
    "deco-sites/std/accounts/vtex.ts": i2$$6,
    "deco-sites/std/accounts/yourViews.ts": i2$$7,
  },
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest satisfies DecoManifest;
